apiVersion: v2
name: redpanda-operator-cluster-topic-helm
description: A Helm chart for managing RedPanda Cluster & Topics 
type: application
version: 0.0.9
appVersion: "1.0.0"
maintainers:
  - name: Albertas Grinkevicius
    email: albertasg@gmail.com
keywords:
  - redpanda
  - gitops
home: https://github.com/albertasg/redpanda-operator-cluster-topic-helm
sources:
  - https://github.com/albertasg/redpanda-operator-cluster-topic-helm
annotations:
  artifacthub.io/changes: |
    - Initial release
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: GitHub
      url: https://github.com/albertasg/redpanda-operator-cluster-topic-helm
    