{{- if .Values.redpandaTopics.enabled }}
{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $defaultClusterRef := .Values.redpanda.clusterRefName | default .Values.redpanda.name }}
{{- range $i, $topic := .Values.redpandaTopics.topics }}
---
apiVersion: cluster.redpanda.com/v1alpha1
kind: Topic
metadata:
  name: {{ $topic.name }}
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
spec:
  partitions: {{ $topic.partitions }}
  replicationFactor: {{ $topic.replicationFactor }}
  cluster:
    clusterRef:
      name: {{- if and $topic.cluster $topic.cluster.clusterRef $topic.cluster.clusterRef.name }}{{ $topic.cluster.clusterRef.name }}{{- else }}{{ $defaultClusterRef }}{{- end }}
  {{- if $topic.config }}
  config:
    {{- toYaml $topic.config | nindent 4 }}
  {{- end }}
  {{- with $topic.extraSpec }}
  # Extra advanced spec fields
  {{ toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }} 